language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('Paulo13') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - service mysql restart